LMG_Customer_Prediction

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
# import seaborn as sns
# import datetime, nltk, warnings
# import matplotlib.cm as cm
# import itertools
# from pathlib import Path
# from sklearn.preprocessing import StandardScaler
# from sklearn.cluster import KMeans
# from sklearn.metrics import silhouette_samples, silhouette_score
# from sklearn import preprocessing, model_selection, metrics, feature_selection
# from sklearn.model_selection import GridSearchCV, learning_curve
# from sklearn.svm import SVC
# from sklearn.metrics import confusion_matrix
# from sklearn import neighbors, linear_model, svm, tree, ensemble
# from wordcloud import WordCloud, STOPWORDS
# from sklearn.ensemble import AdaBoostClassifier
# from sklearn.decomposition import PCA
# from IPython.display import display, HTML
# import plotly.graph_objs as go
# from plotly.offline import init_notebook_mode,iplot
# init_notebook_mode(connected=True)
# warnings.filterwarnings("ignore")
# plt.rcParams["patch.force_edgecolor"] = True
# plt.style.use('fivethirtyeight')
# mpl.rc('patch', edgecolor = 'dimgray', linewidth=1)
# # %matplotlib inline

In [3]:
customer_demo = pd.read_excel('Data/Customer_Demographics.xlsx')
customer_trans=pd.read_excel('Data/Customer_Transaction.xlsx')
stores=pd.read_excel('Data/Store_Master.xlsx')

### UTILITY Functions

In [4]:
def get_basic_details(df):
    print(df.isnull().sum())
    print("\n\nDATA TYPE VALUES\n\n")
    print(df.dtypes)
    print("\n\nDATA Summary\n\n")
    print(df.describe())

In [5]:
print("\n\nCustomer Demo")
get_basic_details(customer_demo)
print("\n\nCustomer Transcation")
get_basic_details(customer_trans)
print("\n\nStores Demo")
get_basic_details(stores)

Customer Demo
Customer_ID             0
Territory               0
Nationality             0
Income_Range            0
Job_Type                0
Marital_Status          0
Gender                  0
State                   0
Language                0
Loyalty_Status          0
Birth_date          17538
Age                 26096
Points               2863
First_txn_dt           33
Last_accr_txn_dt        6
Last_rdm_txn_dt     28419
dtype: int64


DATA TYPE VALUES


Customer_ID           int64
Territory            object
Nationality          object
Income_Range         object
Job_Type             object
Marital_Status       object
Gender               object
State                object
Language             object
Loyalty_Status       object
Birth_date           object
Age                 float64
Points              float64
First_txn_dt         object
Last_accr_txn_dt     object
Last_rdm_txn_dt      object
dtype: object


DATA Summary


        Customer_ID           Age        Points
count  1.000000e+05  73904.000000  97137.000000
mean   1.800000e+15     37.032096    274.889084
std    8.334842e+07      9.319975    541.612278
min    1.800000e+15      1.000000  -1660.000000
25%    1.800000e+15     31.000000     59.000000
50%    1.800000e+15     36.000000    150.000000
75%    1.800000e+15     42.000000    303.000000
max    1.800000e+15    137.000000  37264.000000


Customer Transcation
Territory                0
Business                 0
Year                     0
Week                     0
Store_Code               0
City_Name            39185
Store_Type           39185
Transaction_Type         0
Return_Reason       507635
Customer_ID              0
Invoices                 0
Item_Count               0
Revenue                  0
Discount                 0
Units_Sold               0
dtype: int64


DATA TYPE VALUES


Territory            object
Business             object
Year                  int64
Week                  int64
Store_Code            int64
City_Name            object
Store_Type           object
Transaction_Type     object
Return_Reason        object
Customer_ID           int64
Invoices              int64
Item_Count            int64
Revenue             float64
Discount            float64
Units_Sold            int64
dtype: object


DATA Summary


                Year           Week     Store_Code   Customer_ID  \
count  544649.000000  544649.000000  544649.000000  5.446490e+05
mean     2016.508180      26.875329   60075.307596  1.800000e+15
std         0.500011      15.004671      42.259146  7.484180e+07
min      2010.000000       0.000000   60053.000000  1.800000e+15
25%      2016.000000      16.000000   60057.000000  1.800000e+15
50%      2017.000000      26.000000   60067.000000  1.800000e+15
75%      2017.000000      40.000000   60072.000000  1.800000e+15
max      2017.000000      53.000000   60275.000000  1.800000e+15

            Invoices     Item_Count        Revenue       Discount  \
count  544649.000000  544649.000000  544649.000000  544649.000000
mean        1.167477       5.479867     137.115751      27.722461
std         0.481601       6.583207     200.312213      85.608802
min         1.000000       1.000000   -1689.000000   -1004.000000
25%         1.000000       2.000000      34.000000       0.000000
50%         1.000000       3.000000      84.000000       0.000000
75%         1.000000       7.000000     178.000000      25.000000
max        25.000000     302.000000   30851.000000   12486.000000

          Units_Sold
count  544649.000000
mean        5.375504
std         7.483735
min       -41.000000
25%         1.000000
50%         3.000000
75%         7.000000
max       767.000000


Stores Demo
Territory             0
Business              0
Region                0
Region_Code           0
Store_Code            0
Store_Name            0
Mall_Name             0
Store_Format         25
Sales_Per_Day         0
Store_Launch_Date     0
Train_Test_Store      0
Geo_Field             8
Store_Size_Sq_Ft      0
Customer_Count        4
Total_Revenue         0
dtype: int64


DATA TYPE VALUES


Territory                    object
Business                     object
Region                       object
Region_Code                   int64
Store_Code                    int64
Store_Name                   object
Mall_Name                    object
Store_Format                 object
Sales_Per_Day               float64
Store_Launch_Date    datetime64[ns]
Train_Test_Store             object
Geo_Field                    object
Store_Size_Sq_Ft            float64
Customer_Count              float64
Total_Revenue               float64
dtype: object


DATA Summary


       Region_Code    Store_Code  Sales_Per_Day  Store_Size_Sq_Ft  \
count    35.000000     35.000000      35.000000         35.000000
mean    602.542857  60118.571429    2566.336917      12952.417688
std       1.787915     91.171553    2009.960248      15241.825225
min     601.000000  60053.000000     369.319201       2178.431368
25%     601.000000  60062.500000    1291.529348       6349.130519
50%     602.000000  60071.000000    2101.072259       8792.292763
75%     603.500000  60152.500000    3092.483398      15753.415130
max     606.000000  60301.000000   10861.009520      93125.240189

       Customer_Count  Total_Revenue
count       31.000000   3.500000e+01
mean    107748.774194   3.748174e+07
std      56801.836186   2.347820e+07
min      13669.000000   4.796778e+05
25%      76982.500000   1.892515e+07
50%      88496.000000   4.088288e+07
75%     135841.500000   4.998286e+07
max     263026.000000   9.281707e+07

In [6]:
#TRYING TO Make data frame for a ll

df =pd.merge(pd.merge(customer_demo.drop('Territory', axis=1),customer_trans, on=['Customer_ID']),stores.drop('Business',axis=1) , on =['Store_Code'])

In [7]:
df.isnull().sum()

Customer_ID               0
Nationality               0
Income_Range              0
Job_Type                  0
Marital_Status            0
Gender                    0
State                     0
Language                  0
Loyalty_Status            0
Birth_date            53003
Age                   89003
Points                 3997
First_txn_dt             59
Last_accr_txn_dt          7
Last_rdm_txn_dt       60568
Territory_x               0
Business                  0
Year                      0
Week                      0
Store_Code                0
City_Name             39184
Store_Type            39184
Transaction_Type          0
Return_Reason        507634
Invoices                  0
Item_Count                0
Revenue                   0
Discount                  0
Units_Sold                0
Territory_y               0
Region                    0
Region_Code               0
Store_Name                0
Mall_Name                 0
Store_Format         485707
Sales_Per_Day             0
Store_Launch_Date         0
Train_Test_Store          0
Geo_Field            171138
Store_Size_Sq_Ft          0
Customer_Count            0
Total_Revenue             0
dtype: int64

In [ ]:
df.columns